### ISSUE TITLE
Error when loading not found file

### ISSUE THREAD

**Issue by syre** [pynocchio/pynocchio#85]
I'm getting this error when trying to load a file that is not found:
```
ERROR:pynocchio.main_window_model:Error in load comic! 'File not loaded'
Traceback (most recent call last):
  File "/home/syre/pynocchio/pynocchio/main_window_model.py", line 65, in load
    loader.load(filename)
  File "/home/syre/pynocchio/pynocchio/comic_file_loader_zip.py", line 72, in load
    raise NoDataFindException(message)
pynocchio.exception.NoDataFindException: 'File not loaded'
QIODevice::read (QFile, ":/icons/notCover.png"): device not open
```

**Comment by mstuttgart** [comment]
Hi @syre. Yes, refer a image in resource file. I need to fix this
